GET http://localhost:3001/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJCdWRpIiwiZW1haWwiOiJidWRpQGdtYWlsLmNvbSIsImlhdCI6MTY2NjYxNTQyNSwiZXhwIjoxNjY2NjE1NDQwfQ.OyGmBjLV-pvRZWHjEoCsmkYuEntv908GaYSzuSZ_Oec

###
GET http://localhost:3001/refresh_token

###
POST http://localhost:3001/register
Content-Type: application/json

{
     "name": "Budi",
     "email": "budi@gmail.com",
     "password": "123456",
     "confPassword": "123456"
}

###
POST http://localhost:3001/login
Content-Type: application/json

{
     "email": "budi@gmail.com",
     "password": "123456"
}


###
DELETE http://localhost:3001/logout