GET http://localhost:3001/users

###
POST http://localhost:3001/register
Content-Type: application/json

{
     "name": "Budi",
     "email": "budi@gmail.com",
     "password": "123456",
     "confPassword": "123456"
}

###
POST http://localhost:3001/login
Content-Type: application/json

{
     "email": "tono@gmail.com",
     "password": "123456"
}
